project:
  type: book
  output-dir: _book
  render:
    - index.qmd
    - notebooks/data_exploration.qmd
    - dev.ipynb

book:
  title: "GDPR Fines Regression Analysis"
  author: "David Currie"
  date: "27/11/2023"
  chapters:
    - index.qmd
    - notebooks/data_exploration.qmd
    - dev.ipynb

format:
  html: 
    code-fold: true
    toc: true
    number-sections: true
    number-depth: 3
    css: styles.css
    fig-width: 7.1

jupyter: python3
keep-ipynb: false
execute: 
  enabled: true